import type { ElementCategory, FloorPlanElementType } from "./types";

export type ElementDefinition = {
  type: FloorPlanElementType;
  label: string;
  category: ElementCategory;
  defaultWidth: number;
  defaultHeight: number;
  minWidth: number;
  minHeight: number;
  supportsResize: boolean;
  supportsChildren: boolean;
  supportsRotation: boolean;
  supportsCapacity?: boolean;
  defaultCapacity?: number;
  canContain: FloorPlanElementType[];
  validParents: FloorPlanElementType[] | "floor";
  color: string;
  borderColor: string;
  icon: string;
};

/** Minimum footprint for resizable elements — one grid cell (same as a seat). */
const MIN_CELL = 1;

export const ELEMENT_REGISTRY: Record<FloorPlanElementType, ElementDefinition> = {
  floor: {
    type: "floor",
    label: "Floor",
    category: "structure",
    defaultWidth: 1,
    defaultHeight: 1,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: true,
    supportsRotation: false,
    canContain: ["block", "room", "cabin", "meeting_room", "conference_room", "common_area", "seat", "desk", "pillar", "wall", "door", "entrance", "reception", "stairs"],
    validParents: "floor",
    color: "#f8fafc",
    borderColor: "#cbd5e1",
    icon: "layout-grid",
  },
  block: {
    type: "block",
    label: "Block",
    category: "structure",
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: true,
    supportsRotation: true,
    canContain: ["room", "cabin", "meeting_room", "conference_room", "common_area", "seat", "desk", "workstation", "meeting_table", "pillar", "wall", "door", "entrance", "reception"],
    validParents: "floor",
    color: "#eff6ff",
    borderColor: "#93c5fd",
    icon: "square-stack",
  },
  room: {
    type: "room",
    label: "Room",
    category: "structure",
    defaultWidth: 5,
    defaultHeight: 3,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: true,
    supportsRotation: true,
    supportsCapacity: true,
    defaultCapacity: 5,
    canContain: ["seat", "desk", "workstation", "meeting_table", "pillar", "wall", "door"],
    validParents: ["floor", "block"],
    color: "#f0fdf4",
    borderColor: "#86efac",
    icon: "door-open",
  },
  cabin: {
    type: "cabin",
    label: "Cabin",
    category: "structure",
    defaultWidth: 3,
    defaultHeight: 2,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: true,
    supportsRotation: true,
    supportsCapacity: true,
    defaultCapacity: 1,
    canContain: ["seat", "desk", "workstation"],
    validParents: ["floor", "block"],
    color: "#fef3c7",
    borderColor: "#fcd34d",
    icon: "briefcase",
  },
  meeting_room: {
    type: "meeting_room",
    label: "Meeting Room",
    category: "structure",
    defaultWidth: 6,
    defaultHeight: 5,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: true,
    supportsRotation: true,
    supportsCapacity: true,
    defaultCapacity: 8,
    canContain: ["seat", "desk", "meeting_table", "pillar", "wall", "door"],
    validParents: ["floor", "block"],
    color: "#ede9fe",
    borderColor: "#c4b5fd",
    icon: "users",
  },
  conference_room: {
    type: "conference_room",
    label: "Conference Room",
    category: "structure",
    defaultWidth: 8,
    defaultHeight: 6,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: true,
    supportsRotation: true,
    supportsCapacity: true,
    defaultCapacity: 12,
    canContain: ["seat", "desk", "meeting_table", "pillar", "wall", "door"],
    validParents: ["floor", "block"],
    color: "#fce7f3",
    borderColor: "#f9a8d4",
    icon: "presentation",
  },
  common_area: {
    type: "common_area",
    label: "Common Area",
    category: "structure",
    defaultWidth: 6,
    defaultHeight: 4,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: true,
    supportsRotation: true,
    canContain: ["seat", "desk", "reception", "pillar"],
    validParents: ["floor", "block"],
    color: "#ecfdf5",
    borderColor: "#6ee7b7",
    icon: "coffee",
  },
  seat: {
    type: "seat",
    label: "Seat",
    category: "workspace",
    defaultWidth: 1,
    defaultHeight: 1,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: false,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block", "room", "cabin", "meeting_room", "conference_room", "common_area"],
    color: "#ffffff",
    borderColor: "#cbd5e1",
    icon: "armchair",
  },
  desk: {
    type: "desk",
    label: "Desk",
    category: "workspace",
    defaultWidth: 2,
    defaultHeight: 1,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block", "room", "cabin", "meeting_room", "conference_room", "common_area"],
    color: "#f1f5f9",
    borderColor: "#94a3b8",
    icon: "monitor",
  },
  workstation: {
    type: "workstation",
    label: "Workstation",
    category: "workspace",
    defaultWidth: 2,
    defaultHeight: 2,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block", "room", "cabin", "common_area"],
    color: "#e2e8f0",
    borderColor: "#64748b",
    icon: "laptop",
  },
  meeting_table: {
    type: "meeting_table",
    label: "Meeting Table",
    category: "workspace",
    defaultWidth: 3,
    defaultHeight: 2,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["meeting_room", "conference_room", "room"],
    color: "#ddd6fe",
    borderColor: "#8b5cf6",
    icon: "table",
  },
  reception: {
    type: "reception",
    label: "Reception",
    category: "workspace",
    defaultWidth: 4,
    defaultHeight: 2,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block", "common_area"],
    color: "#dbeafe",
    borderColor: "#3b82f6",
    icon: "concierge-bell",
  },
  pillar: {
    type: "pillar",
    label: "Pillar",
    category: "infrastructure",
    defaultWidth: 1,
    defaultHeight: 2,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block", "room", "cabin", "meeting_room", "conference_room", "common_area"],
    color: "#475569",
    borderColor: "#334155",
    icon: "columns",
  },
  wall: {
    type: "wall",
    label: "Wall",
    category: "infrastructure",
    defaultWidth: 4,
    defaultHeight: 1,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block", "room", "cabin", "meeting_room", "conference_room"],
    color: "#64748b",
    borderColor: "#475569",
    icon: "minus",
  },
  door: {
    type: "door",
    label: "Door",
    category: "infrastructure",
    defaultWidth: 2,
    defaultHeight: 1,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block", "room", "cabin", "meeting_room", "conference_room"],
    color: "#bfdbfe",
    borderColor: "#2563eb",
    icon: "door-open",
  },
  entrance: {
    type: "entrance",
    label: "Entrance",
    category: "infrastructure",
    defaultWidth: 4,
    defaultHeight: 1,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block"],
    color: "#bae6fd",
    borderColor: "#0284c7",
    icon: "log-in",
  },
  stairs: {
    type: "stairs",
    label: "Stairs",
    category: "infrastructure",
    defaultWidth: 2,
    defaultHeight: 3,
    minWidth: MIN_CELL,
    minHeight: MIN_CELL,
    supportsResize: true,
    supportsChildren: false,
    supportsRotation: true,
    canContain: [],
    validParents: ["floor", "block"],
    color: "#e7e5e4",
    borderColor: "#78716c",
    icon: "stairs",
  },
};

export function getElementDefinition(type: FloorPlanElementType): ElementDefinition {
  return ELEMENT_REGISTRY[type];
}

export function toolboxElements(): ElementDefinition[] {
  return Object.values(ELEMENT_REGISTRY).filter((def) => def.type !== "floor");
}

export function canPlaceInParent(
  childType: FloorPlanElementType,
  parentType: FloorPlanElementType | null,
): boolean {
  const def = ELEMENT_REGISTRY[childType];
  if (parentType === null) {
    if (def.validParents === "floor") return true;
    return Array.isArray(def.validParents) && def.validParents.includes("floor");
  }
  if (def.validParents === "floor") return false;
  const parentDef = ELEMENT_REGISTRY[parentType];
  return def.validParents.includes(parentType) && parentDef.canContain.includes(childType);
}
